### ISSUE TITLE
Thanks to gyro for his piper model

### ISSUE THREAD

**Issue by gyroing** [Soebb/persian-tts-bot#1]
Thank you!
 The model is still being trained to achieve the best performance.
Gyro ;)

**Comment by Soebb** [comment]
Amazing, go ahead🙏

**Comment by gyroing** [comment]
> Amazing, go ahead🙏

I suggest you " hazm model " (just pos tagger) 
[Hazm repo](https://github.com/roshan-research/hazm)
to detect kasre ezafeh (my code @🤗)
[تشخیص کسره اضافه](https://huggingface.co/spaces/gyroing/PersianTextCorrection_Hazm)

**Comment by Soebb** [comment]
> > Amazing, go ahead🙏
> 
> I suggest you " hazm model " (just pos tagger) [Hazm repo](https://github.com/roshan-research/hazm) to detect kasre ezafeh (my code @🤗) [تشخیص کسره اضافه](https://huggingface.co/spaces/gyroing/PersianTextCorrection_Hazm)

### Hi, i created [this](https://www.github.com/Soebb/test_hazm) to testing hazm but it gave me below error, can you help?



Step 9/11 : RUN make
---> Running in d61a9d1c114a
g++ -Wall kasre_ezafeh.cpp hazm.cpp -o ezafeh
[91m/usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Py_DECREF': hazm.cpp:(.text+0x54): undefined reference to `_Py_Dealloc' /usr/bin/ld: /tmp/ccf8rq2C.o: in function `Hazm::HazmObject::HazmObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)': hazm.cpp:(.text+0x165): undefined reference to `Py_IsInitialized' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x173): undefined reference to `Py_Initialize' /usr/bin/ld: hazm.cpp:(.text+0x182): undefined reference to `[0m
[91mPyUnicode_FromString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x192): undefined reference to `PyImport_Import' /usr/bin/ld: hazm.cpp:(.text+0x1c0): undefined reference to `PyModule_GetDict' /usr/bin/ld: hazm.cpp:(.text+0x417): undefined reference to `PyDict_New' /usr/bin/ld: hazm.cpp:(.text+0x49f): undefined reference to `PyRun_StringFlags' /usr/bin/ld: hazm.cpp:(.text+0x4fc): undefined reference to `PyUnicode_FromString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x516): undefined reference to `PyDict_GetItem' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x537): undefined reference to `PyObject_CallObject' [0m
[91m/usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::HazmObject::vectorToPyObject(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)': hazm.cpp:(.text+0x6cf): undefined reference to `PyTuple_New' [0m
[91m/usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x748): undefined reference to `PyUnicode_FromString' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::HazmObject::pyObjectToVector[abi:cxx11](_object*)': hazm.cpp:(.text+0x887): undefined reference to `PyTuple_GetItem' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x8a3): undefined reference to `PyUnicode_AsUTF8' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x904): undefined reference to `PyTuple_Size' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x961): undefined reference to `PyList_GetItem' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x97d): undefined reference to `PyUnicode_AsUTF8' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x9d5): undefined reference to `PyList_Size' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::Normalizer::normalize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)': hazm.cpp:(.text+0xc88): undefined reference to `PyObject_GetAttrString' [0m
[91m/usr/bin/ld: [0m
[91mhazm.cpp:(.text+0xcf1): undefined reference to `PyUnicode_FromString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0xd0b): undefined reference to `PyTuple_Pack' /usr/bin/ld: hazm.cpp:(.text+0xd32): undefined reference to `PyObject_CallObject' /usr/bin/ld[0m
[91m: [0m
[91mhazm.cpp:(.text+0xd4e): undefined reference to `PyUnicode_AsUTF8' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::Stemmer::stem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)': hazm.cpp:(.text+0xf72): undefined reference to `PyObject_GetAttrString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0xfdb): undefined reference to `PyUnicode_FromString' /usr/bin/ld: hazm.cpp:(.text[0m
[91m+0xff5): undefined reference to `PyTuple_Pack' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x101c): undefined reference to `PyObject_CallObject' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x1038): undefined reference to `PyUnicode_AsUTF8' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::Lemmatizer::lemmatize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)': hazm.cpp:(.text+0x125c): undefined reference to `PyObject_GetAttrString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x12c5): undefined reference to `PyUnicode_FromString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x12df): undefined reference to `PyTuple_Pack' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x1306): undefined reference to `PyObject_CallObject' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x1322): undefined reference to `PyUnicode_AsUTF8' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::SentenceTokenizer::tokenize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)': hazm.cpp:(.text+0x1524): undefined reference to `PyObject_GetAttrString' [0m
[91m/usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x158d): undefined reference to `PyUnicode_FromString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x15a7): undefined reference to `PyTuple_Pack' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x15ce): undefined reference to `PyObject_CallObject' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::WordTokenizer::tokenize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)': hazm.cpp:(.text+0x17aa): undefined reference to `PyObject_GetAttrString' [0m
[91m/usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x1813): undefined reference to `PyUnicode_FromString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x182d): undefined reference to `PyTuple_Pack' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x1854): undefined reference to `PyObject_CallObject' [0m
[91m/usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::POSTagger::pyObjectToTagsVector(_object*)': hazm.cpp:(.text+0x1bd9): undefined reference to `PyTuple_GetItem' [0m
[91m/usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x1cc0): undefined reference to `PyTuple_Size' [0m
[91m/usr/bin/ld: hazm.cpp:(.text+0x[0m
[91m1d20): undefined reference to `PyList_GetItem' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x1e07): undefined reference to `PyList_Size' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::POSTagger::tagsVectorToPyObject(std::vector<Hazm::POSTagger::TagItem, std::allocator<Hazm::POSTagger::TagItem> > const&)': hazm.cpp:(.text+0x1eb6): undefined reference to `PyTuple_New' [0m
[91m/usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::POSTagger::tag(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)': hazm.cpp:(.text+0x218e): undefined reference to `PyObject_GetAttrString' [0m
[91m/usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x2209): undefined reference to `PyTuple_Pack' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x2230): undefined reference to `PyObject_CallObject' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::Chunker::parse(std::vector<Hazm::POSTagger::TagItem, std::allocator<Hazm::POSTagger::TagItem> > const&)': hazm.cpp:(.text+0x257e): undefined reference to `PyObject_GetAttrString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x25f1): undefined reference to `PyTuple_Pack' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x260c): undefined reference to `PyObject_CallObject' /usr/bin/ld: [0m
[91m/tmp/ccf8rq2C.o: in function `Hazm::Chunker::pyObjectToTreeNode(_object*)': hazm.cpp:(.text+0x26af): undefined reference to `[0m
[91mPyObject_GetAttrString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x2713): undefined reference to `PyObject_GetAttrString' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x277b): undefined reference to `PyObject_CallObject' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x279a): undefined reference to `PyUnicode_AsUTF8' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x27ca): undefined reference to `PyObject_Size' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x27f3): undefined reference to `Py_BuildValue' /usr/bin/ld: [0m
[91mhazm.cpp:(.text+0x280d): undefined reference to `PyObject_GetItem' [0m
[91mcollect2: error: ld returned 1 exit status [0m
[91mmake: *** [Makefile:2: ezafeh] Error 1 [0m
The command '/bin/sh -c make' returned a non-zero code: 2

Process failed. 404 Client Error for http+docker://localhost/v1.42/images/registry.doprax.com:5000/soheybazmoon/borhjv0jijz6dixgiuxuyhqocshvks/json: Not Found ("No such image: registry.doprax.com:5000/soheybazmoo

**Comment by gyroing** [comment]
you should compile with tjis command:
g++ -Wall kasre_ezafeh.cpp hazm.cpp hazm.h -o ezafeh $(python3.xx-config --ldflags --embed)
which xx is your current python on your system (linux)
also  you should adress the Python.h in hazm.cpp file.
[fatal error: Python.h: No such file or directory](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory/21530768#21530768)
#include <Python.h>
i  set header path manully in my device .
i will realese the binary for linux aarch64 and amd64 in repo.

**Comment by gyroing** [comment]
> you should compile with this command: g++ -Wall kasre_ezafeh.cpp hazm.cpp hazm.h -o ezafeh $(python3.xx-config --ldflags --embed) which xx is your current python on your system (linux) also you should adress the Python.h in hazm.cpp file. [fatal error: Python.h: No such file or directory](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory/21530768#21530768) #include <Python.h> i change the header path manully in my device . i will realese the binary for linux aarch64 and amd64 in repo.

my contact : amir@navabi.net
send email to get my phone to call to solve your problem

**Comment by Soebb** [comment]
> > you should compile with tjis command: g++ -Wall kasre_ezafeh.cpp hazm.cpp hazm.h -o ezafeh $(python3.xx-config --ldflags --embed) which xx is your current python on your system (linux) also you should adress the Python.h in hazm.cpp file. [fatal error: Python.h: No such file or directory](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory/21530768#21530768) #include <Python.h> i chand thevheader path manully in my device . i will realese the binary for linux aarch64 and amd64 in repo.
> 
> my contact : [amir@navabi.net](mailto:amir@navabi.net) send email to get my phone to call to solve your problem

Thanks, it solved just by adding -lpython3.10 option.
https://stackoverflow.com/q/74838922/18090903
